actualizacion de textos.
tandil-dev/tandil.dev pull request #11
Opened 2019-11-18 11:48 UTC by fMercury

2019-11-18 15:07 UTC, MatiasOS requested changes
Algunos detalles

2019-11-18 15:07 UTC, MatiasOS commented on index.html
> +                <h2 class="u-heading-v6__title g-font-weight-700 g-font-size-26 g-brd-primary mb-0">Trabajo duro</h2>
![trabajo-duro](https://user-images.githubusercontent.com/5481398/69063490-570afa80-09fb-11ea-9404-428f5449dfe7.png)

Fijate que quedó medio raro el `Metricas del trabajo duro`. Tenemos que re pensar esta parte

2019-11-18 15:07 UTC, MatiasOS commented on index.html
![desalineado](https://user-images.githubusercontent.com/5481398/69063629-9df8f000-09fb-11ea-8943-2a647316b541.png)

Con los cambios en los textos, esta sección quedó bastante desalineada.

Por otro lado, se te ocurre que podemos reemplazar alguna de estas métricas por otras más relevantes? 
Quizás ocultar la sección hasta más adelante

2019-11-18 15:09 UTC, MatiasOS commented on index.html
> +                      Técnico informáico de Mar del Plata, Bs.As., Argentina
un typo en `informáico`. Perdiste la `t` :laughing:

2019-11-19 19:04 UTC, fMercury commented on index.html
> +                <h2 class="u-heading-v6__title g-font-weight-700 g-font-size-26 g-brd-primary mb-0">Trabajo duro</h2>
En referencia al **título** o a la **sección en general**

2019-11-19 19:11 UTC, fMercury commented on index.html
el de contribuidores hay que sacarlo (hay una sección exclusiva para eso) 
igual  por el momento ocultarloscapaz es lo mejor hasta que sean mayores.

2019-11-19 19:11 UTC, fMercury commented on index.html
> +                      Técnico informáico de Mar del Plata, Bs.As., Argentina
Thanks

2019-11-19 19:59 UTC, MatiasOS approved these changes

2019-11-19 20:15 UTC, merged